### PR TITLE
use cidv1

### PR DESCRIPTION
**Pull request by wngr**

### CODE REVIEW

**Review by dvc94ch — APPROVED** [review]
Thanks

**Comment by wngr** [comment]
@dvc94ch could you provide access to this org's members to the crate so that I can release 0.2.0 (see above)?

**Comment by dvc94ch** [comment]
not sure if that's possible. added a crates team which can be added with `cargo owner --add github:ipfs-rust:crates`.

**Comment by wngr** [comment]
Thanks, that worked https://crates.io/crates/unixfs-v1/0.2.0

**Pull request merged**
